"""
Domain model for auto-fix proposals.

AutoFixProposal represents a detected issue that requires operator
approval before execution.  Proposals are generated by
AutoFixService.detect_all() and never persisted — they exist only
for the duration of the review dialog.
"""
from dataclasses import dataclass, field
from typing import Optional, Callable

# Proposal type constants
FIX_SOURCE_CLEANUP = "source_cleanup"
FIX_TB_ESCALATION = "tb_escalation"
FIX_DEAD_DEVICE = "dead_device"
FIX_DUPLICATE_CLEANUP = "duplicate_cleanup"

# Severity constants (for display ordering)
FIX_SEV_HIGH = "HIGH"
FIX_SEV_MEDIUM = "MEDIUM"
FIX_SEV_LOW = "LOW"

# Sort rank: lower = more urgent
FIX_SEV_RANK = {
    FIX_SEV_HIGH: 0,
    FIX_SEV_MEDIUM: 1,
    FIX_SEV_LOW: 2,
}

# Human-readable type labels
FIX_TYPE_LABELS = {
    FIX_SOURCE_CLEANUP: "Remove Weak Source",
    FIX_TB_ESCALATION: "Escalate TB",
    FIX_DEAD_DEVICE: "Dead Device Alert",
    FIX_DUPLICATE_CLEANUP: "Remove Duplicates",
}


@dataclass
class AutoFixProposal:
    """A proposed auto-fix action awaiting operator approval."""
    fix_type: str                        # FIX_* constant
    severity: str                        # FIX_SEV_* constant
    target: str                          # username, device_name, or source_name
    description: str                     # human-readable explanation
    detail: str                          # additional context (e.g. "wFBR=0.2%, 150 follows")
    execute: Optional[Callable] = None   # callable that performs the fix; None for info-only
    metadata: Optional[dict] = None      # extra data for logging after execution

    @property
    def is_actionable(self) -> bool:
        """True if this proposal can be executed (has a callable)."""
        return self.execute is not None

    @property
    def type_label(self) -> str:
        """Human-readable label for the fix type."""
        return FIX_TYPE_LABELS.get(self.fix_type, self.fix_type)

    @property
    def sev_rank(self) -> int:
        """Numeric rank for sorting (lower = more urgent)."""
        return FIX_SEV_RANK.get(self.severity, 99)
